### ISSUE TITLE
# of instances of AttestCertsAttribute

### ISSUE THREAD

**Issue by hannestschofenig** [lamps-wg/csr-attestation#10]
> >>
> >>     A CSR MUST contain at most 1 AttestCertsAttribute. In the case where the CSR contains multiple instances of AttestAttribute representing multiple attestations, all necessary certificates MUST be contained in the same instance of AttestCertsAttribute.
> >>
> >>  
> >>
> >> Perhaps to make the wording easier, shall we change the description to “A CSR MUST only contain  exactly one AttestCertsAttribute”?
> >
> > Sounds like a good idea.
> 
> It's only a good idea if you ignore:
> 
> > [[MO]] But a CSR can also contain zero instances of AttestCertsAttribute, for example if you know that the RP already knows your public key then you have no need to transmit any certs. Alternatively, maybe there exists an Attestation format where the certs are buried inside the AttestStatement.
> > [[MO]] I could change the wording to “A CSR MUST contain 0 or 1 instances of AttestCertsAttribute” if that is clearer?
> 
> Given that you can't have less than zero instances of an attribute in a CSR, "at most one" is the same as "zero or one".   I wouldn't object to a change to zero or one, but I would to "exactly one".  If you always require exactly one, you will most likely be duplicating information that's available in the body of the actual attestation statement included in the AttestAttribute (cf Webauthn attestation formats).
> 
> Mike

**Comment by ounsworth** [comment]
I was coming here to open the same issue.

Tasks:
1. Re-word "at most 1" to "zero or one".
2. Add text making it clear that the AttestCertsAttribute is optional and SHOULD be omitted if the attestation statement format being carried already includes the cert chain, as is the case with WebAuthn -- see [WebAuthn-2 s. 8.2](https://www.w3.org/TR/webauthn-2/#sctn-packed-attestation).

**Comment by ounsworth** [comment]
This has been addressed.
