### ISSUE TITLE
Include a CMW example in the appendix

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/csr-attestation#109]
https://datatracker.ietf.org/doc/html/draft-ietf-rats-msg-wrap-04#name-transporting-cmw-in-x509-me

Complication is that the OID for that is not yet allocated, so in order to not slow down the CSR Attest draft, CMW would need to ask for early allocation in order to produce a complete example containing the final OID.

Discussion is needed about whether the CMW OID should be allocated within the new registry created by the CSR Attest draft "SMI Security for PKIX Evidence Statement Formats" Registry. That would require requesting early allocation of both the registry and the CMW OID within it. Possibly we should also re-name it to be broader than just Evidence.

FYI @thomas-fossati , @hannestschofenig

**Comment by ounsworth** [comment]
@nedmsmith is this issue closed by PR #125 ?

**Comment by thomas-fossati** [comment]
> https://datatracker.ietf.org/doc/html/draft-ietf-rats-msg-wrap-04#name-transporting-cmw-in-x509-me
> 
> Complication is that the OID for that is not yet allocated, so in order to not slow down the CSR Attest draft, CMW would need to ask for early allocation in order to produce a complete example containing the final OID.

IANA has allocated codepoint 35, see:
https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#smi-numbers-1.3.6.1.5.5.7.1
