### ISSUE TITLE
Re-use of RATS’s Conceptual Messages Wrapper (CMW)

### ISSUE THREAD

**Issue by hannestschofenig** [lamps-wg/csr-attestation#11]
Remark from Thomas:

> It looks very much like RATS’s CMW [1], except CMW builds on media types rather than OIDs to provide the typing information (and therefore does not need bootstrapping and maintenance of yet another IANA registry).
>  
> IMO it’d be better if we could converge on one only encap format.  Not only to avoid unnecessary duplication, but also because from the point of view of the RA/CA an AttestStatement is just a byte string that needs to be forwarded to their trusted attestation Verifier.  The RA/CA does not need to know which type of attestation statement it’s dealing with, as long as it knows that it’s a blob that the attestation Verifier will make sense of.
> 
> [1] https://datatracker.ietf.org/doc/html/draft-ftbs-rats-msg-wrap-03#section-3.1

Proposal from Russ:
> 
> PKIXAttestIdentifier ::= CHOICE {
>    coap-content-format INTEGER (0..65535),
>    media-type IA5String }
> 
> CMOptions ::= ENUMERATED {
>    reference-values,
>    endorsements,
>    evidence,
>    attestation-results }
> 
>   PKIX-ATTESTATION ::= CLASS {
>       &id  PKIXAttestIdentifier UNIQUE,
>       &AttestType,
>       &cm CMOptions OPTIONAL
>   } WITH SYNTAX {
>       TYPE &AttestType IDENTIFIED BY &id [FOR &cm]
>   }
> 
>   PKIXAttestation{PKIX-ATTESTATION:PKIXAttestSet} ::= SEQUENCE {
>       attestID      PKIX-ATTESTATION.&id({PKIXAttestSet}),
>       attestType    CMOptions OPTIONAL,
>       attestValue   PKIX-ATTESTATION.&AttestType({PKIXAttestSet}{@attestID})
>   }
> 
> PKIXAttestSet PKIX-ATTESTATION ::= { ... }
> 

Suggestion from Thomas:

> I'd be more radical and just put the CMW as-is into an OCTET STRING.

**Comment by ounsworth** [comment]
We should respond to this on-list.
The core question here is whether LAMPS / CSR should be specifying encodings other than ASN.1.

**Comment by thomas-fossati** [comment]
> The core question here is whether LAMPS / CSR should be specifying encodings other than ASN.1.

LAMPS shouldn't specify core attestation formats, they already exist and are specified by other SDOs (e.g., FIDO, TCG, W3C) and IETF groups (e.g,. RATS).

The suggestion of using CMW (wrapped in a ASN.1 OCTET STRING) fully decouples attestation formats from the CSR format, making the latter scalable.

**Comment by nedmsmith** [comment]
> We should respond to this on-list. The core question here is whether LAMPS / CSR should be specifying encodings other than ASN.1.

What is the rationale for redefining something that is already defined but doesn't use ASN.1 as the data definition language?
