### ISSUE TITLE
Freshness "out-of-scope" vs "not required"

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/csr-attestation#15]
Since the document discusses it, it is by definition, in-scope.

Perhaps change the paragraph to say "is not required", or "is left up to the discretion of protocol designers and implementors" or something similar.

The whole paragraph about freshness probably needs a re-write for consistency since it currently reads like it was written by two authors (which it was).

**Comment by carl-wallace** [comment]
I don't think "not required" is what you want here but your second option seems fine. Maybe something like "while this specification does not impose any freshness requirements, an attestation format or certificate management protocol may impose freshness requirements".

**Comment by ounsworth** [comment]
MSJ:
> the freshness is less relevant, because we expect the protection of the key will never get worse (except for a compromise, which is not our problem today).

We could add wording to the security consideration to this effect -- ie that since we are asserting immutable / non-roll-backable properties of the private key's storage, freshness is less relevant.

That said, this feels like it's getting pretty deep into the semantics of a key attestation / platform attestation; which we are trying to avoid making assumptions about in this transport draft.
