### ISSUE TITLE
Change "CSR" to "Certificate Signing Request"

### ISSUE THREAD

**Issue by henkbirkholz** [lamps-wg/csr-attestation#18]
In this context, https://www.rfc-editor.org/materials/abbrev.expansion.txt expands CSR to Certificate Signing Request(s) and not Certification Signing Requests. For consistence, I'd also recommend to expand CA to Certificate Authority.

**Comment by henkbirkholz** [comment]
And yes, I am aware of RFC 2986 and that it specifies `CertificationRequest` for PKCS#10. RFC 2986 also does not define CSR. Some terminology cleanup in summarizing that and then provide the reader with clear guidance an what means can only be beneficial, I think.

**Comment by mcr** [comment]
Only CA=> Certification Authority. Not the other words you used.

**Comment by henkbirkholz** [comment]
So you think "Certification Signing Requests" is a real term that you use today? Did you look at RFCed's abbrev list?

**Comment by henkbirkholz** [comment]
RFC 4949 expands CA to "Certification Authority"
RFCed expands CA to "Certification Authority" or "Certificate Authority"

So => Certification Authority

RFC 4949 does not contain CSR
RFCed expands CSR to "Certificate Signing Request"

Would you like to redefine the RFCed listed (aka you can just write it in an I-D and do not have to expand it ever) meaning?

**Comment by ounsworth** [comment]
Closing, as per LAMPS thread.
