### ISSUE TITLE
Document build is failing

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/csr-attestation#24]
Both my local `make` and the compiler in the github action are getting the same error:

```
*** YAML syntax error: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
```

To my eyes it looks the same as other documents that do compile, so I don't know what's going on here. Help?
@hannestschofenig , @mcr , @henkbirkholz

**Comment by hannestschofenig** [comment]
Was just a problem with the references -- even though the error description does not give that impression
