### ISSUE TITLE
Explain in section 3 why the Passport Model is not applicable to CSRs

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/csr-attestation#37]
@henkbirkholz has brought this up 3 times now; might as well add a paragraph.

**Comment by henkbirkholz** [comment]
Will start a PR this week.

**Comment by hannestschofenig** [comment]
Didn't see your message. Have a look at the reference PR to see whether it matches your understanding.

**Comment by ounsworth** [comment]
Closed with #56
