### ISSUE TITLE
Explain what the "TCG DICE ConceptualMessageWrapper in CSR" Section shows us

### ISSUE THREAD

**Issue by hannestschofenig** [lamps-wg/csr-attestation#55]

**Comment by hannestschofenig** [comment]
We need a bit of text explaining the reader what they are seeing in the example.

My additional question is whether this example illustrates a pattern for re-using the CMW and thereby addressing https://github.com/lamps-wg/csr-attestation/issues/11

**Comment by thomas-fossati** [comment]
> My additional question is whether this example illustrates a pattern for re-using the CMW

Likely so, and that's great.   To that respect I think the text proposed in https://github.com/lamps-wg/csr-attestation/commit/882aa7ea05e84e3d6b087bd980c554412b7a81c0 should be made more explicit.

(Also, it'd be good to stick a ref to the "RATS Conceptual Messages Wrapper" document alongside DICE arch 1.1.)
