### ISSUE TITLE
Review MSJ's feedback

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/csr-attestation#60]
https://mailarchive.ietf.org/arch/msg/spasm/iiSZymLu19uVBXfdt25HxhuLglw/

**Comment by ounsworth** [comment]
This was discussed over breakfast at 118.

Out of that discussion we have two changes to make to the document:

1)
Add a MUST statement in the EvidenceBundle definition section, something like:

> All of the EvidenceStatements within a given EvidenceBundle MUST be verifiable with the certificates contained within that EvidenceBundle, or with certificates already known to the verifier. Specifically, verifiers MUST NOT be forced to search the certificates contained in a different EvidenceBundle; if multiple EvidenceBundles require the same certificate(s) in order to verify their EvidenceStatements, then those certificates MUST be duplicated into all EvidenceBundle that requires them.


2)
Add an Implementation Consideration with a worked example of "the slider".

> Section X
Provide an example with:
[EvidenceStatement1] signed by [ [SigningCert1], [DeviceRootCert], [ManufacturerRootCert] ]
[EvidenceStatement2] signed by [ [SigningCert2], [DeviceRootCert], [ManufacturerRootCert] ]
where the [DeviceRootCert] and [ManufacturerRootCert] are common to the two evidence statements. This specification provides multiple ways to encode this scenario with the goals of allowing implementers to choose whether they wish to optimize for bandwidth by including a minimal and de-duplicated certificate bundle), or to optimize for computation by providing one-to-one associations of EvidenceStatements and the certificate chains that validate them.

> Section X.1: Bandwidth-optimized encoding
If the implementer wishes to optimize for bandwidth, then the CSR producer MAY merge these two certificate chains into a single EvidenceBundle:
```
attr-evidence ATTRIBUTE ::= {
  IDENTIFIED BY id-aa-evidenceStatement
  SEQUENCE OF EvidenceBundle {
    EvidenceBundle ::= SEQUENCE
    {
      evidence  SEQUENCE OF EvidenceStatement {
         [EvidenceStatement1], [EvidenceStatement2]
      }
      certs SEQUENCE OF CertificateAlternatives {
         [SigningCert1], [SigningCert2], [DeviceRootCert], [ManufacturerRootCert]
      }
    }
  }
}
```
Note that bandwidth optimization in this way forces extra computation on the validator (certificate path building) since the certs is not a single ordered certificate chain.

> Section X.2: Computation-optimized encoding
This example can equivalently be encoded as two independent EvidenceBundles:
```

attr-evidence ATTRIBUTE ::= {
  IDENTIFIED BY id-aa-evidenceStatement
  SEQUENCE OF EvidenceBundle {
    EvidenceBundle ::= SEQUENCE
    {
      evidence  SEQUENCE OF EvidenceStatement {
         [EvidenceStatement1]
      }
      certs SEQUENCE OF CertificateAlternatives {
         [SigningCert1], [DeviceRootCert], [ManufacturerRootCert]
      }
    },
    EvidenceBundle ::= SEQUENCE
    {
      evidence  SEQUENCE OF EvidenceStatement {
         [EvidenceStatement2]
      }
      certs SEQUENCE OF CertificateAlternatives {
         [SigningCert2], [DeviceRootCert], [ManufacturerRootCert]
      }
    }
  }
}
```
This encoding optimizes for computation in a couple of different ways. First, the CSR producer does not need to merge and de-duplicate the two certificate chains, in fact this encoding could allow the CSR producer to opaquely copy the evidence statements and cert chains without needing to parse them. Second, the verifier does not need to do any complex certificate path building because each evidence statement is bundled one-to-one with the certificate chain against which it can be validated.

**Comment by russhousley** [comment]
Nit: define 

~~~
EvidenceBundles ::= SEQUENCE OF EvidenceBundle
~~~

**Comment by ounsworth** [comment]
I created #71 to address Russ' nit. I am closing this Issue.
