### ISSUE TITLE
Adding the ability to convey Attestation Results in CSR

### ISSUE THREAD

**Issue by hannestschofenig** [lamps-wg/csr-attestation#62]
Ned mentioned that the trusted path routing work requires the use of an attestation result.

**Comment by hannestschofenig** [comment]
Use case 2: RA interacts with the Verifier to obtain an Attestation Result and then includes the Attestation Result into the CSR to the CA

**Comment by ounsworth** [comment]
Does this require structural changes to the EvidenceBundle?
Can you not pretend that in AttestationResult is an Evidence, and put it inside an EvidenceStatement?

Also, Use Case 2 is weird; normally the RA does not have the End Entity's private key, so the RA can't modify the CSR and re-sign it; so it would have to carry the Attestation Result next to the CSR. Unless the RA can "counter-sign" the CSR such that the CSR is no longer self-signed, but instead signed with an RA key, but that's getting weird.

**Comment by ounsworth** [comment]
My first reaction is that this is getting a bit too scope-creepy; models where the Attester has interacted with the Verifier prior to creating the CSR is outside the scope of this diagram:

~~~
                              .-------------.
                              |             | Compare Evidence
                              |   Verifier  | against
                              |             | policy
                              '--------+----'
                                   ^   |
                          Evidence |   | Attestation
                                   |   | Result
                                   |   v
 .------------.               .----|----------.
 |            +-------------->|----'          | Compare Attestation
 |  Attester  |   Evidence    | Relying       | Result against
 |            |   in CSR      | Party (RA/CA) | policy
 '------------'               '---------------'
~~~

**Comment by mcr** [comment]
Mike Ounsworth ***@***.***> wrote:
    > My first reaction is that this is getting a bit too scope-creepy;
    > models where the Attester has interacted with the Verifier prior to
    > creating the CSR is outside the scope of this diagram:

I mostly agree.
I think that there are perhaps needs for the passport model for some HSMs,
but it should be out of scope for revision one.

**Comment by Akretsch** [comment]
> Also, Use Case 2 is weird; normally the RA does not have the End Entity's private key, so the RA can't modify the CSR and re-sign it; so it would have to carry the Attestation Result next to the CSR. Unless the RA can "counter-sign" the CSR such that the CSR is no longer self-signed, but instead signed with an RA key, but that's getting weird.
If you use CRMF-centric enrollment protocols like CMP there would be a standard way to do, see https://www.rfc-editor.org/rfc/rfc9483.html#section-5.2.3.2

**Comment by ounsworth** [comment]
Meeting with Hannes and Henk.
Decision: considering Passport Model, or the hybrid Passport-Background that Andreas proposes, are out-of-scope for this draft. We will probably need to add Attestation Results to CSR at some point, but that should be a new draft and new top-level CSR attribute / extension.
