### ISSUE TITLE
Evidence vs Edorsements vs ReferenceValues

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/csr-attestation#63]
This is just a naming issue; we use the term "Evidence" everywhere, but of course you can carry any type of Attestation conceptual message here. We should probably find a broader term to use.

What's the right umbrella term? "conceptual message content"? (that sounds like it's implying a CMW-structured data, which we are not implying).

Maybe "AttestationData" ? "ConveyenceStatement" ?

**Comment by mcr** [comment]
The container is for Evidence.  You can also carry kangaroos in it, but that doesn't mean you should.
I don't think a broader term is helpful unless you really expect to carry something else.

**Comment by ounsworth** [comment]
Awesome. Sounds like we're sticking with "Evidence". I am closing this issue.
