### ISSUE TITLE
OIDs for Evidence Formats need to be defined / listed somewhere

### ISSUE THREAD

**Issue by hannestschofenig** [lamps-wg/csr-attestation#65]
# The Problem

Developers implementing this specification will have a problem to find OIDs for the Evidence formats they are using. There is no repository that allows someone to just search for the values. Instead, developers need to search in the relevant specifications, which can be time consuming.

# Proposed Solution

The suggestion is to have IANA maintain a list of OID values for Evidence formats, a short description (name), and a reference to the specification where more details can be found, and a change controller. The change controller refers to the party that can update, or otherwise change the entry in the table. It does not list the controller of the OID itself.

Here is an example of how this table would look like.

```
 +-----------------------------------------------------------------------+
 | OID              | Name               | Reference | Change Controller |
 +------------------+--------------------+-----------+-------------------+
 | 2 23 133 5 4 10  | DICE Evidence      |   [1]     |  IESG             |
 | 2 23 133 5 4 9   | CMW                |   [1,2]   |  IESG             |
 +------------------+--------------------+-----------+-------------------+
```

References:

[1] "DICE Attestation Architecture", URL: https://trustedcomputinggroup.org/wp-content/uploads/DICE-Attestation-Architecture-Version-1.1-Revision-17_1August2023.pdf

[2] "RATS Conceptual Messages Wrapper", URL: https://datatracker.ietf.org/doc/draft-ietf-rats-msg-wrap

**Comment by hannestschofenig** [comment]
@henkbirkholz @ounsworth How does this look like?

**Comment by ounsworth** [comment]
For me, the important question is whether we need to block publication of the CSR ATTEST spec while we resolve this?

**Comment by hannestschofenig** [comment]
@mwiseman-byid going to provide OIDs from TCG

**Comment by hannestschofenig** [comment]
PR #83 incorporated
