### ISSUE TITLE
Small tweak on freshness feasability

### ISSUE THREAD

**Issue by henkbirkholz** [lamps-wg/csr-attestation#84]
`Epochs also require (unidirectional) communication. None of these things are practical when interacting with Hardware Security Modules (HSM).`

... in the CSR context considering HSMs employed by CAs/RAs.
Instead of leaving the reader with "none of mechanisms about freshness for Evidence apply", maybe a quick pointer to the qualities of system isolation to be expected are useful?

**Comment by henkbirkholz** [comment]
related to: https://github.com/lamps-wg/csr-attestation/issues/80#issuecomment-1915208748

**Comment by ounsworth** [comment]
@henkbirkholz I tweaked a sentence in https://github.com/lamps-wg/csr-attestation/commit/c5921f2c2b09ce9804c61a400fb06556a25e7d3a
