### ISSUE TITLE
Introduction: Clarifying Assumptions

### ISSUE THREAD

**Issue by hannestschofenig** [lamps-wg/csr-attestation#86]
Ned & Monty suggest to provide further text to explain what the assumptions for creating an interoperable implementation are. 

Questions to be answered, for example, are: 

- What other specifications do need to be read/implemented when the Verifier is not co-located with the RA/CA?
- How is the Attestation Result content?
- What is conveyed in the Certificate about the attestation verification?

**Comment by ounsworth** [comment]
I think my responses here are:

> What other specifications do need to be read/implemented when the Verifier is not co-located with the RA/CA?
> How is the Attestation Result content?

What API the Verifier presents to the RA/CA is out of scope for this CSR wire-format document.

> What is conveyed in the Certificate about the attestation verification?

The contents of issued certificates are out of scope for this CSR wire-format document.

**Comment by mcr** [comment]
> I think my responses here are:
> 
> > What other specifications do need to be read/implemented when the Verifier is not co-located with the RA/CA?
> > How is the Attestation Result content?
> 
> What API the Verifier presents to the RA/CA is out of scope for this CSR wire-format document.

I agree.  It would however, be good if anyone who has a protocol that they intend to use confirms that they have all the bits they need.  That needn't be a blocker.

> > What is conveyed in the Certificate about the attestation verification?
> 
> The contents of issued certificates are out of scope for this CSR wire-format document.

I agree that this is true.  Is there any CABFORUM view on this?  Is there a policy OID that they would telling CAs to include if they comply, and can that document be informatively cited as motivation for this work?

**Comment by ounsworth** [comment]
@mcr 

> Is there any CABFORUM view on this? Is there a policy OID that they would telling CAs to include if they comply, and can that document be informatively cited as motivation for this work?

I think the prevailing attitude is that the Code Signing BRs require that the CA verify that the subscriber's keys are in hardware. How the CA does that is up to the CA with Attestation being one of the acceptable methods; various signed letters and screenshots of admin consoles being another. So IF (Code_Signing); THEN hardware check must have been done.

Here, you know what, the Intro already says this:

> The Code-Signing Baseline Requirements [CSBR] document is an example of such a policy that has been published by the CA Browser Forum and specifies certain properties, such as non-exportability, which must be enabled for storing publicly-trusted code-signing keys. Other policies influence

I'll strengthen that to include a section reference , just for you ;)

> The Code-Signing Baseline Requirements [[CSBR](https://lamps-wg.github.io/csr-attestation/draft-ietf-lamps-csr-attestation.html#CSBR)] document, **specifically section 6.2.7.3 Private key storage for Signing Services**, is an example of such a policy that has been published by the CA Browser Forum and specifies certain properties, such as non-exportability, which must be enabled for storing publicly-trusted code-signing keys. Other policies influence
